blank_issues_enabled: false
contact_links:
  - name: FantasyXI Community Discussions
    url: https://github.com/Stanley471/FantasyXI/discussions
    about: Ask architectural questions, brainstorm ideas, or seek support from the maintainers.
